### ISSUE TITLE
MessageAttributes of AWS.SQS.Message undefined

### ISSUE THREAD

**Issue by JonasDiscovery** [ssut/nestjs-sqs#12]
@SqsMessageHandler(/** name: */ 'OPEN_TICKETS', /** batch: */ false)
  public async openTickets(message: AWS.SQS.Message) {
    const body = JSON.parse(message.Body);
    console.log(body);
    console.log(message.MessageAttributes);
  }

Result : 
{ test: 'test', test2: 2 }
undefined

Hi,

The message doesn't contains attributes. When I use the polling method from aws console, I see message attributes.

![image](https://user-images.githubusercontent.com/57357515/121655464-ed4fb700-ca9e-11eb-892e-f189e25e4b02.png)

![image](https://user-images.githubusercontent.com/57357515/121655861-37d13380-ca9f-11eb-8163-f9408534888e.png)

Thanks in advance,
Jonas

**Comment by RodolpheGohard** [comment]
I'm interested in this issue, I need to retrieve MessageAttributes such as `ApproximateFirstReceiveTimestamp` and `ApproximateReceiveCount`. Any updates or workaround ?

**Comment by JohnAdamsy** [comment]
> For anyone wondering how you'd be able to receive all the message attributes for each message, you can configure your SQS handler like this:
> 
> ```
> @Module({
>   imports: [
>     SqsModule.register({
>       consumers: [
>         {
>           name: 'your-sqs-queue-name',
>           queueUrl: 'your-sqs-queue-url',
>           messageAttributeNames: ['All']
>         }
>       ],
>       producers: [],
>     }),
>   ],
> })
> class AppModule {}
> ```

@fabiofcferreira Thanks for the save, dude!  🙌
