### ISSUE TITLE
Update dependencies to allow nestjs v8

### ISSUE THREAD

**Issue by vladshoob** [ssut/nestjs-sqs#17]
Could not resolve dependency:
npm ERR! peer @nestjs/common@"^6.10.11 || ^7.0.0" from @ssut/nestjs-sqs@1.0.0

**Comment by ssut** [comment]
https://github.com/ssut/nestjs-sqs/issues/16#issuecomment-929828105

**Comment by vladshoob** [comment]
@ssut, thanks for commenting and maintaining this package.

Unfortunately `peerDependencies` still blocking update.

```
  "peerDependencies": {
    "@nestjs/common": "^6.10.11 || ^7.0.0",
    "@nestjs/core": "^6.10.11 || ^7.0.0"
  }
 ```
