### ISSUE TITLE
Dependency injection? 

### ISSUE THREAD

**Issue by Ciboulette** [ssut/nestjs-sqs#2]
```
import { Injectable } from "@nestjs/common";
import { SqsMessageHandler } from "@ssut/nestjs-sqs";
import { SyncsService } from "../syncs.service";

import { Jobtypes } from "./job.types";
export const SYNC_WORKSPACE_QUEUE_NAME = "syncs_workspace";

export const SYNCS_QUEUE_NAME = "syncs";

@Injectable()
export class SyncsConsumer {
  constructor(private readonly syncsService: SyncsService) {
    console.log(syncsService);
  }

  @SqsMessageHandler(SYNCS_QUEUE_NAME)
  public async processJob(message: AWS.SQS.Message) {
    const job = JSON.parse(message.Body);

    try {
      switch (job.type) {
        case Jobtypes.syncOne:
          console.log("received ", job);
          await this.syncsService.execute(job);

          break;

        default:
          throw `No job with type: ${job.type} exists in syncs queue`;
      }
    } catch (error) {
      console.log("error", error);
    }
  }
}
```

I've created this class as a consumer, and when receiving the message the syncService is not injected, is-it normal?

**Comment by ssut** [comment]
Probably not normal. Can you let me know syncsService exists in the constructor?

**Comment by Ciboulette** [comment]
The console.log in the constructor return 'undefined'

**Comment by ssut** [comment]
So it's not related to this project I think. You will have to import the module in which SyncsService belongs.

**Comment by Shpadoinkle** [comment]
@Ciboulette  Did you ever find a solution for this?  Currently having the same problem after swapping from Redis. 

All constructor values are undefined once inside the SqsMessageHandler

**Comment by Shpadoinkle** [comment]
For others who stumble across this same issue. 

If it is the same issues we encountered.  It was due to converting existing Request scoped to use this queue worker, yet still having our processes scoped to the Request that now no longer exists once the message is retrieved from sqs.

**Comment by bryanmaraujo544** [comment]
I am still having this issue, how can I "remove the scope from Injectable"?
