### ISSUE TITLE
Not able to connect to LocalStack Sqs URL

### ISSUE THREAD

**Issue by VivekPNs** [ssut/nestjs-sqs#58]
Hi Folks,

I have been struggling to figure out why Im not able to connect to LocalStack sqs URL. I have setup [LocalStack](https://docs.localstack.cloud/user-guide/aws/sqs/) to run the queue in my local. I was able to send and receive the message using cli commands and also I was able to publish the message to this queue from my other non nestjs application but the ssut/nestjs-sqs throws the below error and I'm not sure why.

```
api/node_modules/sqs-consumer/dist/errors.js:40
    const sqsError = new SQSError(message);
                     ^
SQSError: SQS receive message failed: The address https://sqs.us-east-1.amazonaws.com/ is not valid for this endpoint.
    at toSQSError (/api/node_modules/sqs-consumer/dist/errors.js:40:22)
    at Consumer.receiveMessage (/api/node_modules/sqs-consumer/dist/consumer.js:173:43)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by agnarok** [comment]
Im facing the same issue the only solution i found was to instantiate my own SQS Client
```js
const sqsClient = new SQSClient({
     region,
     endpoint: 'LOCALSTACK_URL'
}) ;
```

**Comment by VivekPNs** [comment]
> Im facing the same issue the only solution i found was to instantiate my own SQS Client
> 
> ```js
> const sqsClient = new SQSClient({
>      region,
>      endpoint: 'LOCALSTACK_URL'
> }) ;
> ```

@agnarok Could you please let me know where exactly you instantiate the client and consume it? I have own service file and I'm consuming the message like below

`@Injectable()
export class QueueHandler {
  constructor(private pService: PService) {}
  @SqsMessageHandler(queueName, false)
  async handleMessage(message: SQS.Message) {
    const logger = new Logger(this.handleMessage.name);
    try {
//Business logic
    } catch (error) {
      logger.error(error.message, error.stack);
      throw error;
    }
  }`

**Comment by agnarok** [comment]
SQSClient is an option for the consumer so your module should be something like this :arrow_down: 
```js
import { Module } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { SqsModule } from '@ssut/nestjs-sqs';

@Module({
  imports: [
    ProposalsModule,
    SqsModule.registerAsync({
      useFactory: (configService: ConfigService) => {
        return {
          consumers: [
            {
              name: configService.getOrThrow('AWS_SQS_QUEUE_NAME'),
              queueUrl: 'http://localhost:4566/000000000000/queueName',
              sqs = new SQSClient({
                  region: 'REGION',
                  endpoint: 'LOCALSTACK_URL'
               }) ;            
             },
          ],
          producers: [],
        };
      },
      inject: [ConfigService],
    }),
  ],
  providers: [QueueHandler],
}) 
```

**Comment by VivekPNs** [comment]
@agnarok I'm really confused now. `SQSClient ` is not part of this library so, not sure how do I instantiate it. Also is `queueUrl ` and `endpoint` are same?

**Comment by agnarok** [comment]
@VivekPNs SqSClient is used internally in the lib, so you would need to import in your project to use it like i suggested.

Also, no endpoint and the queueUrl are not the same. The endpoint is used in the AWS SDK for pooling data

**Comment by VivekPNs** [comment]
@agnarok But SqSClient is not part of the @ssut/nestjs-sqs library. Could you provide some snippets to understand better?

**Comment by ahmad-ite** [comment]
Finally, it works for me 
this is a full code for ConsumerModule
don't forget to import `ConsumerModule` in the app module 

`import { ConfigModule, ConfigService } from '@nestjs/config';
import { Module } from '@nestjs/common';
import { SqsModule } from '@ssut/nestjs-sqs';
import { ConsumerService } from './consumer.service';
import { SQSClient } from '@aws-sdk/client-sqs';

@Module({
  imports: [
    ConfigModule,
    SqsModule.registerAsync({
      imports: [ConfigModule], // Import the ConfigModule to use the ConfigService
      useFactory: async (configService: ConfigService) => {
        const accessKeyId = configService.get<string>('sqs.accessKeyId');
        const secretAccessKey = configService.get<string>(
          'sqs.secretAccessKey',
        );
   
        // Retrieve the required configuration values using ConfigService
        return {
          consumers: [
            {
              name: configService.get<string>('sqs.queue_name'), // name of the queue
              queueUrl: configService.get<string>('sqs.url'), // url of the queue
              region: configService.get<string>('sqs.region'), // using the same region for the producer
              batchSize: 10, // number of messages to receive at once
              terminateGracefully: true, // gracefully shutdown when SIGINT/SIGTERM is received
              sqs:new SQSClient({
                region:configService.get<string>('sqs.region'),
                credentials: {
                  accessKeyId: accessKeyId,
                  secretAccessKey:secretAccessKey
                }
             })
            },
          ],
          producers: [],
        };
      },
      inject: [ConfigService],
    }),
  ],
  controllers: [],
  providers: [ConsumerService],
  exports: [ConsumerService],
})
export class ConsumerModule {}
`

**Comment by ahmad-ite** [comment]
@VivekPNs

**Comment by VivekPNs** [comment]
Yup, I did the same way and it works. Thank you.

**Comment by rbonestell** [comment]
I apologize for cracking open an old issue, but I'm unable to find any more information on what I've found here.
This issue and one other article both have this attribute in the consumer options:
```terminateGracefully: true, // gracefully shutdown when SIGINT/SIGTERM is received```

Where did this come from and what did it do? I simply want to ensure that my NestJS app completes processing the message it's currently handling before terminating on a SIGINT or SIGTERM from ECS, might this help?

Cheers and thanks in advance!

**Comment by ddrummond-allio** [comment]
Dropping a note here mostly b/c I know I'm going to be troubleshooting this same issue in ~5 years and will have forgotten WTF I did to fix it.

I had this same issue where the Nest.js app using this library couldn't communicate w/ the SQS queue I created in Localstack. The specific error I was getting was
```
/opt/transaction-monitoring/node_modules/.pnpm/sqs-consumer@11.1.0_@aws-sdk+client-sqs@3.664.0/node_modules/sqs-consumer/dist/cjs/errors.js:60
const sqsError = new SQSError(message);
                 ^
```

My setup was different though. I was using docker compose to spin up 2 services a `localstack` service and a `transaction-monitoring-svc`. The Nest.js/SQS consumer lived in the `transaction-monitoring-svc` container and the SQS Queue obviously lived in the `localstack` container. 

So when registering the SqsModule I had to use `http://localstack:4566` instead of `http://localhost:4566` as the endpoint url, which is a subtle difference, but very necessary so that docker can resolve the IP address for the localstack container.

Here's a snippet showing how I registered the SqsClient

```js
import { Module } from '@nestjs/common';
import { ConfigModule, ConfigService } from '@nestjs/config';
import { SQSClient } from '@aws-sdk/client-sqs';
import { SqsModule } from '@ssut/nestjs-sqs';

@Module({
  imports: [
    ConfigModule.forRoot({
      isGlobal: true,
      load: [configuration],
    }),
    HttpModule,
    SqsModule.registerAsync({
      imports: [ConfigModule],
      useFactory: (cfg: ConfigService) => {
        return {
          consumers: [{
            name:'transactions',
            queueUrl: cfg.get('transactionMonitoringQueueUrl'),
            sqs: cfg.get('env') === 'development' ? new SQSClient({
              region: 'us-east-1',
              endpoint: 'http://localstack:4566' // This was the http://localhost:4566 which would have worked if I was running the app from my laptop instead of within a docker contianer.
            }) : new SQSClient()
          }]
        }
      },
      inject: [ConfigService]
    })
  ]
})
export class AppModule {};
```
