### ISSUE TITLE
Version 2.3.0 isn't published to npm

### ISSUE THREAD

**Issue by smacker** [ssut/nestjs-sqs#79]
CI failed and the package is not available:
https://github.com/ssut/nestjs-sqs/actions/runs/8766156011/job/24058004947#step:8:41

**Comment by awuzi** [comment]
hi, any updates on it ?

**Comment by AbdelrahmanManz** [comment]
Hey, this has been down for a while, any updates?

**Comment by smacker** [comment]
@LuiFerPereira as a temporary workaround you can install this package: https://www.npmjs.com/package/@smacker/nestjs-sqs it is built from the master branch of this repository

**Comment by ssut** [comment]
I apologize for the delay to this CI issue. I've been so busy and could not give my best effort to fix the publish issue until now. I have just fixed it and published v2.3.0.
